---
name: Check Code Quality

on:
  push:
    branches: [main]

jobs:
  Code-Quality:
    name: CodeQuality
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install black
        pip install isort
        pip install flake8

    - name: Run black
      run: black .
    - name: Run isort
      run: isort .
    - name: Run flake8
      run: flake8 .
