---
name: set-up code quality
run-name: ${{ github.actor }} is running
on:
  push:
    branches: [main]

jobs:
  code-quality:
    strategy:
      fail-fast: false
    matrix:
      python-version: [3.8, 3.9, 3.10]
      os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: set up
      - uses:
        with: actions/setup-python@v2
        python-version: ${{ matrix.python-version }}

      - name: Check Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          pip install black
          pip install flake8
          pip install isort

      - name: Run black
        run: black .
      - name: Run isort
        run: isort .
      - name: Run flake8
        run: flake8 .
